"""empty message

Revision ID: 8f886fc039b0
Revises: 
Create Date: 2017-11-10 00:06:59.841857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f886fc039b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'additional_links', ['id'])
    op.create_unique_constraint(None, 'content', ['id'])
    op.create_unique_constraint(None, 'maps', ['id'])
    op.create_unique_constraint(None, 'poi', ['id'])
    op.create_unique_constraint(None, 'stories', ['id'])
    op.alter_column('story_names', 'story_name',
               existing_type=sa.VARCHAR(),
               nullable=0)
    op.create_unique_constraint(None, 'story_names', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_names', type_='unique')
    op.alter_column('story_names', 'story_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'stories', type_='unique')
    op.drop_constraint(None, 'poi', type_='unique')
    op.drop_constraint(None, 'maps', type_='unique')
    op.drop_constraint(None, 'content', type_='unique')
    op.drop_constraint(None, 'additional_links', type_='unique')
    # ### end Alembic commands ###
